import { Button, Center, Container, Flex, Input, SimpleGrid, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { FormEventHandler, useState } from "react";
import { RankingCard } from "../components/RankingCard";

const Home: NextPage = () => {
  const router = useRouter();
  const [slug, setSlug] = useState("");
  const onSubmit: FormEventHandler<HTMLFormElement> = (e) => {
    e.preventDefault();
    console.log(slug);
    router.push(`/${slug}`);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container as="main" pt="4" maxW="container.lg">
        <Center>
          <Text fontSize="24">デジタルスコアをはかってみよう</Text>
        </Center>
        <form onSubmit={onSubmit}>
          <Flex justifyItems="center">
            <Center pr="1">@</Center>
            <Input onChange={(e) => setSlug(e.target.value)} display="inline-block" />
            <Button ml="4">検索</Button>
          </Flex>
        </form>

        <SimpleGrid minChildWidth="320px" gap="4" mt="4">
          <RankingCard title="Youtuber" items={["はじめしゃちょー", "ヒカキン", "セイキン"]} />
          <RankingCard title="政治家" items={["麻生太郎", "菅直人", "河野太郎"]} />
        </SimpleGrid>
      </Container>
    </div>
  );
};

export default Home;
